version: "3"
services:
  nginx:
      image: mokhaled3003/nginx
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - userManagement
        - filterProducts
        - orders     
  userManagement:
    image: mokhaled3003/userManagement
    environment:
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD 
      MYSQL_DB: $MYSQL_DB 
      MYSQL_HOST: $MYSQL_HOST 
  filterProducts:
    image: mokhaled3003/filterProducts
    environment:
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD 
      MYSQL_DB: $MYSQL_DB 
      MYSQL_HOST: $MYSQL_HOST 
  orders:
    image: mokhaled3003/orders
    environment:
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD 
      MYSQL_DB: $MYSQL_DB 
      MYSQL_HOST: $MYSQL_HOST  
  