version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mokhaled3003/reverseproxy 
  userManagement:
    build:
      context: ../UserManagement
    image: mokhaled3003/user-management
  filterProducts:
    build:
      context: ../FilterProducts
    image: mokhaled3003/filter-products
  orders:
    build:
      context: ../OrderProducts
    image: mokhaled3003/orders